CREATE TABLE IF NOT EXISTS usuarios_admin (
  id SERIAL PRIMARY KEY,
  usuario VARCHAR(80) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  rol VARCHAR(40) NOT NULL DEFAULT 'Administrador',
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS productos (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(160) NOT NULL,
  precio NUMERIC(10, 2) NOT NULL CHECK (precio >= 0),
  imagen TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  disponible BOOLEAN NOT NULL DEFAULT true,
  etiqueta VARCHAR(80),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
